version: 2
jobs:
  build:
    docker:
      - image: rohithbb433/dockerimagedem:test
       
    steps:
      - checkout


      - run: google-chrome --version

      - save_cache:
          key: node_modules-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
            - "Project/node_modules"

      - run: google-chrome --version


      - run: sleep 30s


      - run:
          name: Test Run
          command: |
            protractor configurationFile/RunnerConf.js