version: 2
jobs:
  build:
    docker:
      - image: rohithbb433/dockerimagedem:test
       
    steps:
      - checkout


      - run: google-chrome --version
      
      - run: sleep 30s


      - run:
          name: Test Run
          command: |
            protractor configurationFile/RunnerConf.js