version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11-browsers
        environment:          
          DBUS_SESSION_BUS_ADDRESS: /dev/null
    steps:
      - checkout


      - run: google-chrome --version 69.0.3497.81
      
      - save_cache:
          key: node_modules-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
            - "./node_modules"


      - run:
          name: NPM Install
          command: |
            npm install


      - run:
          name: Install Protractor
          command: |
            sudo npm i -g protractor


      - run:
          name: WebDriver Update
          command: | 
            ./node_modules/.bin/webdriver-manager update --versions.chrome 69.0.3497.81    
            ./node_modules/.bin/webdriver-manager start --versions.chrome 69.0.3497.81de
          background: true

      - run:
          name: WebDriver Update Selenium
          command: |      
            sudo webdriver-manager update
          background: true


      - run: sleep 30


      - run:
          name: Test Run
          command: |
            protractor configurationFile/RunnerConf.js