version: 2
jobs:
  build:
    docker:
      - image: circleci/node:current-browsers
        environment:          
          DBUS_SESSION_BUS_ADDRESS: /dev/null
    steps:
      - checkout


      - run: google-chrome --version 69.0.3497.81
      
      - save_cache:
          key: node_modules-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
            - "Project/node_modules"

      - run: google-chrome --version

      - run:
          name: NPM Install
          command: |
            npm install


      - run:
          name: Install Protractor
          command: |
            sudo npm i -g protractor


      # - run:
      #     name: WebDriver Update Selenium
      #     command: |      
      #        webdriver-manager update --versions.chrome 69.0.3497.81
      #     background: true



      - run:
          name: WebDriver Update
          command: | 
             node ./node_modules/.bin/webdriver-manager update --versions.chrome 96.0.4664.110
             node ./node_modules/.bin/webdriver-manager start --versions.chrome 96.0.4664.110
          background: true


      - run: sleep 30s


      - run:
          name: Test Run
          command: |
            protractor configurationFile/RunnerConf.js